version: '3.1'
services:
  practice-nn-modeling:
    build: .
    ports:
      - 8889:8888
    volumes:
      - ./notebooks/:/notebooks
    environment:
      TZ: Asia/Tokyo
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root . --NotebookApp.password=${JUPYTER_SHA1}
